[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[build.environment]
  NODE_VERSION = "12.10.0"
  RUBY_VERSION = "2.6.2"
[[redirects]]
  from = "https://technovangelist.com/notes/*"
  to = "publish.obsidian.md\s"
  status = 200
  force = true
