backend:
  name: github
  repo: technovangelist/technovangelist.com
publish_mode: editorial_workflow
media_folder: "static/images"
collections:
  - name: "posts"
    label: "Post"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "talks"
    label: "Talk"
    folder: "src/talks"
    create: true
    slug: "{{year}}-{{month}}-{{conference}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Conference", name: "conference", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "URL", name: "url", widget: "string", required: false}
      - {label: "Conference URL", name: "conferenceurl", widget: "string", required: false}
      - {label: "SpeakerDeck ID", name: "speakerdeckid", widget: "string", required: false}
      - {label: "Content", name: "body", widget: "markdown"}